[toolchain]
package_manager = "npm"

[features]
resolution = true
skip-lint = false

[programs.localnet]
flash_pool = "7fMKkQ9dbkMf1FGTv4vZ1m8bgBX1PKehVS6gkDn84Trv"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
